name: Build and Upload JAR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Create result directory
        run: mkdir -p result

      - name: Compile Java files
        run: |
          mkdir -p build
          javac -d build src/*.java

      - name: Create JAR file
        run: |
          cd build
          jar cvfe ../result/stock-trading.jar Main *.class
          cd ..

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add result/stock-trading.jar
          git commit -m "Build: Update JAR file" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
